### ISSUE TITLE
Font size formula input field

### ISSUE THREAD

**Issue by lavaloop-official** [c-w/mathquill4quill#96]
Hello everyone, I think the font in the input is just way to small. Any idea how to increase the size? Here is a screenshot to show you what I mean:
![Screenshot 2023-08-06 185721](https://github.com/c-w/mathquill4quill/assets/132557870/059df655-2618-471e-8ea3-fe6517734876)

**Comment by c-w** [comment]
Does it work for you to modify the properties of the input field in CSS like this:

```css
.mathquill4quill-mathquill-input {
  font-size: 20px;
}
```
